name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy
      cancel-in-progress: true
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_CLIENT_SECRET }}
          tags: tag:ci
          use-cache: "true"

      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          echo "100.94.227.1 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII0uMX0SCi7y/fggooWpB6JwNwlq2fKrwPjEj2iGr2xC" >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          scp -r .output/* ${{ secrets.USERNAME }}@${{ secrets.TS_HOST }}:/root/wydawajka-server

      - name: Restart service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.TS_HOST }}
          username: ${{ secrets.USERNAME }}
          script: |
            systemctl restart wydawajka
